[zh-cn]
  languageName = "简体中文"
  weight = 1
  [zh-cn.params]
    dateFormat = "2006-01-02"
    description = "我们共同的笔记"
    keywords = "爱, 笔记, 情侣"
    [zh-cn.params.archive]
      dateFormat = "01-02"
